### ISSUE TITLE
implement advantages

### ISSUE THREAD

**Issue by addam128** [TAnhMinh/pv260_tennis#3]
I implemented basic scoring that simply stops at 40, and added a test that checks if advantage is set in a 40-40 situation.

After implementing this,  winning on advantage if the other has <40 should be tested, and the situation when both players get an advantage, so it resets to 40-40.

**Comment by frolajos** [comment]
nice

**Comment by addam128** [comment]
added new tests to check advantage resetting and winner setting

**Comment by frolajos** [comment]
nitpick: the project should be runnable after each commit and new tests should fail. Not the build.

**Comment by addam128** [comment]
failing build due to error in test == failing test, the program should run and pass all previously passing tests after a change in the source, the same is not required after adding a test

**Comment by frolajos** [comment]
ok then, advantages implemented
